# pnpm workspace configuration
# Defines which directories contain workspace packages

packages:
  # Applications that will be deployed
  - "apps/*"

  # Shared packages/libraries
  - "packages/*"

  # Firebase Cloud Functions
  - "functions"

